name: 'Terraform Init'
description: 'Initialize Terraform with Azure backend'

inputs:
  working_directory:
    description: 'Working directory'
    required: false
    default: '.'
  backend_resource_group:
    description: 'Backend resource group'
    required: true
  backend_storage_account:
    description: 'Backend storage account'
    required: true
  backend_container:
    description: 'Backend container'
    required: false
    default: 'tfstate'
  backend_key:
    description: 'State file key'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Terraform Init
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        terraform init \
          -backend-config="resource_group_name=${{ inputs.backend_resource_group }}" \
          -backend-config="storage_account_name=${{ inputs.backend_storage_account }}" \
          -backend-config="container_name=${{ inputs.backend_container }}" \
          -backend-config="key=${{ inputs.backend_key }}"
