# =============================================================================
# LEVEL 1: COMPOSITE ACTION - Terraform Init
# =============================================================================
# Reusable action for initializing Terraform with remote backend
# =============================================================================

name: 'Terraform Init'
description: 'Initialize Terraform with Azure remote backend'
author: 'Azure Landing Zone Lab'

inputs:
  resource_group:
    description: 'Backend resource group name'
    required: true
  storage_account:
    description: 'Backend storage account name'
    required: true
  container:
    description: 'Backend container name'
    required: false
    default: 'tfstate'
  state_key:
    description: 'State file key (e.g., lab.terraform.tfstate)'
    required: true
  working_directory:
    description: 'Working directory for Terraform'
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: Terraform Init
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        terraform init \
          -backend-config="resource_group_name=${{ inputs.resource_group }}" \
          -backend-config="storage_account_name=${{ inputs.storage_account }}" \
          -backend-config="container_name=${{ inputs.container }}" \
          -backend-config="key=${{ inputs.state_key }}"
        
        echo "## 📦 Backend Initialized" >> $GITHUB_STEP_SUMMARY
        echo "- Resource Group: \`${{ inputs.resource_group }}\`" >> $GITHUB_STEP_SUMMARY
        echo "- Storage Account: \`${{ inputs.storage_account }}\`" >> $GITHUB_STEP_SUMMARY
        echo "- State Key: \`${{ inputs.state_key }}\`" >> $GITHUB_STEP_SUMMARY
