name: 'Security Scan'
description: 'Run tfsec and Checkov security scans'

inputs:
  working_directory:
    description: 'Directory to scan'
    required: false
    default: '.'
  soft_fail:
    description: 'Continue on findings'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Run tfsec
      uses: aquasecurity/tfsec-action@v1.0.3
      with:
        working_directory: ${{ inputs.working_directory }}
        soft_fail: ${{ inputs.soft_fail }}
      continue-on-error: true

    - name: Run Checkov
      uses: bridgecrewio/checkov-action@v12
      with:
        directory: ${{ inputs.working_directory }}
        framework: terraform
        soft_fail: ${{ inputs.soft_fail }}
      continue-on-error: true
