name: 'Terraform Apply'
description: 'Apply Terraform plan'

inputs:
  working_directory:
    description: 'Working directory'
    required: false
    default: '.'
  plan_file:
    description: 'Plan file to apply'
    required: false
    default: 'tfplan'

runs:
  using: 'composite'
  steps:
    - name: Terraform Apply
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: terraform apply -auto-approve ${{ inputs.plan_file }}
