name: 'Terraform Plan'
description: 'Run Terraform plan with change detection'

inputs:
  working_directory:
    description: 'Working directory'
    required: false
    default: '.'
  var_file:
    description: 'Variables file path'
    required: true
  plan_file:
    description: 'Output plan file name'
    required: false
    default: 'tfplan'

outputs:
  has_changes:
    description: 'Whether plan has changes'
    value: ${{ steps.plan.outputs.has_changes }}
  add:
    description: 'Resources to add'
    value: ${{ steps.summary.outputs.add }}
  change:
    description: 'Resources to change'
    value: ${{ steps.summary.outputs.change }}
  destroy:
    description: 'Resources to destroy'
    value: ${{ steps.summary.outputs.destroy }}

runs:
  using: 'composite'
  steps:
    - name: Terraform Plan
      id: plan
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        set +e
        set -o pipefail
        terraform plan \
          -var-file="${{ inputs.var_file }}" \
          -out=${{ inputs.plan_file }} \
          -detailed-exitcode \
          -no-color 2>&1 | tee plan_output.txt
        EXITCODE=${PIPESTATUS[0]}
        if [ $EXITCODE -eq 0 ]; then
          echo "has_changes=false" >> $GITHUB_OUTPUT
        elif [ $EXITCODE -eq 2 ]; then
          echo "has_changes=true" >> $GITHUB_OUTPUT
        else
          exit 1
        fi

    - name: Parse Summary
      id: summary
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        ADD=$(grep -oP '\d+(?= to add)' plan_output.txt || echo "0")
        CHANGE=$(grep -oP '\d+(?= to change)' plan_output.txt || echo "0")
        DESTROY=$(grep -oP '\d+(?= to destroy)' plan_output.txt || echo "0")
        echo "add=$ADD" >> $GITHUB_OUTPUT
        echo "change=$CHANGE" >> $GITHUB_OUTPUT
        echo "destroy=$DESTROY" >> $GITHUB_OUTPUT
