[CmdletBinding()]
param(
    [switch]$Check
)

$ErrorActionPreference = "Stop"
$repoRoot = Split-Path -Parent $PSScriptRoot
$configPath = Join-Path $repoRoot ".terraform-docs.yml"

if (-not (Get-Command terraform-docs -ErrorAction SilentlyContinue)) {
    throw "terraform-docs 0.24.0 is required. See CONTRIBUTING.md for installation instructions."
}

function Write-TerraformDocumentation {
    param(
        [Parameter(Mandatory)]
        [string]$ModulePath,
        [Parameter(Mandatory)]
        [string]$OutputPath,
        [Parameter(Mandatory)]
        [string]$Title
    )

    $generated = & terraform-docs markdown table --config $configPath $ModulePath
    if ($LASTEXITCODE -ne 0) {
        throw "terraform-docs failed for $ModulePath"
    }

    # Heredoc defaults inherit the checkout line endings. Normalize escaped
    # CRLF sequences so Windows and Linux generate byte-equivalent references.
    $generated = $generated -replace '\\r\\n', '\n'
    $body = ($generated -join [Environment]::NewLine).Trim()
    $content = "# $Title$([Environment]::NewLine)$([Environment]::NewLine)> Generated by scripts/generate-terraform-docs.ps1. Do not edit the tables manually.$([Environment]::NewLine)$([Environment]::NewLine)$body$([Environment]::NewLine)"

    if ($Check) {
        if (-not (Test-Path -LiteralPath $OutputPath)) {
            throw "Generated Terraform documentation is missing: $OutputPath"
        }

        $existing = [System.IO.File]::ReadAllText($OutputPath)
        if ($existing -ne $content) {
            throw "Generated Terraform documentation is stale: $OutputPath. Run scripts/generate-terraform-docs.ps1 and commit the result."
        }

        return
    }

    [System.IO.File]::WriteAllText($OutputPath, $content, [System.Text.UTF8Encoding]::new($false))
}

Write-TerraformDocumentation -ModulePath $repoRoot -OutputPath (Join-Path $repoRoot "TERRAFORM.md") -Title "Terraform reference"

$moduleRoots = Get-ChildItem -Path (Join-Path $repoRoot "modules"), (Join-Path $repoRoot "landing-zones") -Filter "main.tf" -File -Recurse |
    Where-Object { $_.FullName -notmatch '[\\/]\.terraform[\\/]' } |
    ForEach-Object { $_.Directory.FullName } |
    Sort-Object -Unique

foreach ($moduleRoot in $moduleRoots) {
    $relativePath = [System.IO.Path]::GetRelativePath($repoRoot, $moduleRoot).Replace("\", "/")
    Write-TerraformDocumentation -ModulePath $moduleRoot -OutputPath (Join-Path $moduleRoot "README.md") -Title "Terraform module: $relativePath"
}
