name: 'Terraform Setup'
description: 'Setup Terraform and Azure authentication'

inputs:
  terraform_version:
    description: 'Terraform version'
    required: false
    default: '1.9.0'
  azure_credentials:
    description: 'Azure credentials JSON'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform_version }}
        terraform_wrapper: false

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ inputs.azure_credentials }}
